FROM ubuntu:14.04
MAINTAINER matt

RUN apt-get update
RUN apt-get install -y python-dev
RUN apt-get install -y python-pip

COPY requirements.txt /work/requirements.txt
RUN pip install -U -r /work/requirements.txt

ADD . /work/

WORKDIR /work

CMD ["python", "result_logger.py"]